-- MySQL Script generated by MySQL Workbench
-- 05/13/16 02:46:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characters` ;

CREATE TABLE IF NOT EXISTS `characters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `items_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `items_types` ;

CREATE TABLE IF NOT EXISTS `items_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `items_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `items_models` ;

CREATE TABLE IF NOT EXISTS `items_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `items` ;

CREATE TABLE IF NOT EXISTS `items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `model` INT NOT NULL,
  `type` INT NOT NULL,
  `quality` INT NOT NULL,
  `grade` INT NOT NULL,
  `weight` INT NOT NULL,
  `slot` INT NOT NULL,
  `material` INT NOT NULL,
  `consumable` TINYINT(1) NOT NULL,
  `destructible` TINYINT(1) NOT NULL,
  `durable` TINYINT(1) NOT NULL,
  `equippable` TINYINT(1) NOT NULL,
  `reusable` TINYINT(1) NOT NULL,
  `stackable` TINYINT(1) NOT NULL,
  `upgradable` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `items_type_fk_idx` (`type` ASC),
  INDEX `items_model_fk_idx` (`model` ASC),
  CONSTRAINT `items_type_fk`
    FOREIGN KEY (`type`)
    REFERENCES `items_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `items_model_fk`
    FOREIGN KEY (`model`)
    REFERENCES `items_models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventories` ;

CREATE TABLE IF NOT EXISTS `inventories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `character` INT NOT NULL,
  `capacity` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`, `character`),
  INDEX `inv_char_fk_idx` (`character` ASC),
  CONSTRAINT `inv_char_fk`
    FOREIGN KEY (`character`)
    REFERENCES `characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipments` ;

CREATE TABLE IF NOT EXISTS `equipments` (
  `character` INT NOT NULL,
  `helm` INT NOT NULL,
  `neck` INT NOT NULL,
  `armor` INT NOT NULL,
  `gloves` INT NOT NULL,
  `waist` INT NOT NULL,
  `pants` INT NOT NULL,
  `boots` INT NOT NULL,
  `ring1` INT NOT NULL,
  `ring2` INT NOT NULL,
  `hand_left` INT NOT NULL,
  `hand_right` INT NOT NULL,
  PRIMARY KEY (`character`),
  CONSTRAINT `eq_char_fk`
    FOREIGN KEY (`character`)
    REFERENCES `characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams` ;

CREATE TABLE IF NOT EXISTS `teams` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilds` ;

CREATE TABLE IF NOT EXISTS `guilds` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

CREATE TABLE IF NOT EXISTS `locations` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shops` ;

CREATE TABLE IF NOT EXISTS `shops` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventories_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventories_items` ;

CREATE TABLE IF NOT EXISTS `inventories_items` (
  `inventory` INT NOT NULL AUTO_INCREMENT,
  `nr` INT NOT NULL,
  `item` INT NOT NULL,
  UNIQUE INDEX `inventory_UNIQUE` (`inventory` ASC),
  UNIQUE INDEX `item_UNIQUE` (`item` ASC),
  PRIMARY KEY (`inventory`, `nr`),
  CONSTRAINT `ii_item_fk`
    FOREIGN KEY (`item`)
    REFERENCES `items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ii_inv_fk`
    FOREIGN KEY (`inventory`)
    REFERENCES `inventories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
